title:              Kaushal Sarda
email:              kaushalsarda222166@gmail.com
description:        Decoding security things with Kaushal
author:             Kaushal Sarda
# baseurl:            "/"
# url:                "https://kaushalsarda.github.io"

# Social Profiles
# twitter_username:   
github_username:    kaushalsarda
# facebook_username:  
instagram_username:  kaushal_232
linkedin_username: kaushalsarda232

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
