title:              Kaushal Sarda
email:              kaushal.sarda@gmail.com
description:        Decoding security things with Kaushal
author:             Kaushal Sarda
baseurl:            "/"
url:                "https://kaushalsarda.github.io"

# Social Profiles
twitter_username:   kaushalsarda
github_username:    kaushalsarda
facebook_username:  kaushalsarda
instagram_username:  kaushalsarda
linkedin_username: kaushalsarda

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
